name: bloc_pattern
description: Example BLoC
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^3.0.1  
  cupertino_icons: ^0.1.2
  meta: ^1.1.6
  equatable: ^0.2.0
  http: ^0.12.0
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  flutter_webview_plugin: ^0.3.7
  easy_localization: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter  
  mockito: ^4.1.1  
flutter:
  uses-material-design: true
  assets:
    - "lib/resources/en-US.json"
